---
title: "Exploration of Chicago Car Crash Data"
author: "Kevin Thompson, Dilruksha Jayaweera, Heber Nielsen, Sangrae Cho, Kumaraiah Pradeepkumar"
date: |
  Data Science Program, Southern Methodist University, USA \break
lang: en-US
class: man
figsintext: true
numbersections: true
encoding: UTF-8
bibliography: crashes.bib
biblio-style: apalike
output:
  bookdown::pdf_document2:
     citation_package: natbib
     keep_tex: true
     toc: false
header-includes:
   - \usepackage{amsmath}
   - \usepackage[utf8]{inputenc}
   - \usepackage[T1]{fontenc}
   - \usepackage{setspace}
   - \usepackage{hyperref}
   - \onehalfspacing
   - \setcitestyle{round}
   - \newcommand\numberthis{\addtocounter{equation}{1}\tag{\theequation}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

\section{Introduction}

  Car accidents are no trivial matter in the United States. Roughly 800 car accidents occur every day in Illinois alone \citep{tribune}. Our project is to develop models to both predict and explain a subset of these entirely avoidable accidents in Chicago, Illinois. OpenWeather's historical weather database and the city government of Chicago's website to construct these models and insights. These datasets include factors that are widely believed to contribute to higher accident rates, such as weather, time, location, road conditions, and so forth.

  The primary goal of our exploration is to explore useful features for predicting the number of accidents in a given police shift in location clusters called "police beats".
  
```{python preprocessing}
import pandas as pd
import matplotlib.pyplot as plt 

pd.options.display.width = 0
pd.set_option('precision', 2)

crashes = pd.read_csv("data/ChicagoCrashesPerHour2.csv")
print(crashes.describe())
```



