---
title: "MissingData"
author: "Kevin Thompson"
date: "January 22, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(naniar)
library(furrr)
crashes = read_csv("../../data/TrafficCrashesChicago.csv", col_types = cols(
  RD_NO = col_character(),
  CRASH_DATE_EST_I = col_factor(),
  CRASH_DATE = col_datetime(format = "%m/%d/%Y %H:%M:%S %p"),
  POSTED_SPEED_LIMIT = col_double(),
  TRAFFIC_CONTROL_DEVICE = col_factor(),
  DEVICE_CONDITION = col_factor(),
  WEATHER_CONDITION = col_factor(),
  LIGHTING_CONDITION = col_factor(),
  FIRST_CRASH_TYPE = col_factor(),
  TRAFFICWAY_TYPE = col_factor(),
  LANE_CNT = col_double(),
  ALIGNMENT = col_factor(),
  ROADWAY_SURFACE_COND = col_factor(),
  ROAD_DEFECT = col_factor(),
  REPORT_TYPE = col_factor(),
  CRASH_TYPE = col_factor(),
  INTERSECTION_RELATED_I = col_factor(),
  NOT_RIGHT_OF_WAY_I = col_factor(),
  HIT_AND_RUN_I = col_factor(),
  DAMAGE = col_factor(),
  DATE_POLICE_NOTIFIED = col_datetime(format = "%m/%d/%Y %H:%M:%S %p"),
  PRIM_CONTRIBUTORY_CAUSE = col_factor(),
  SEC_CONTRIBUTORY_CAUSE = col_factor(),
  STREET_NO = col_character(),
  STREET_DIRECTION = col_factor(),
  STREET_NAME = col_character(),
  BEAT_OF_OCCURRENCE = col_factor(),
  PHOTOS_TAKEN_I = col_factor(),
  STATEMENTS_TAKEN_I = col_factor(),
  DOORING_I = col_factor(),
  WORK_ZONE_I = col_factor(),
  WORK_ZONE_TYPE = col_factor(),
  WORKERS_PRESENT_I = col_factor(),
  NUM_UNITS = col_double(),
  MOST_SEVERE_INJURY = col_factor(),
  INJURIES_TOTAL = col_double(),
  INJURIES_FATAL = col_double(),
  INJURIES_INCAPACITATING = col_double(),
  INJURIES_NON_INCAPACITATING = col_double(),
  INJURIES_REPORTED_NOT_EVIDENT = col_double(),
  INJURIES_NO_INDICATION = col_double(),
  INJURIES_UNKNOWN = col_double(),
  CRASH_HOUR = col_integer(),
  CRASH_DAY_OF_WEEK = col_integer(),
  CRASH_MONTH = col_integer(),
  LATITUDE = col_double(),
  LONGITUDE = col_double(),
  LOCATION = col_character()
))

```


```{r summary}
summary(crashes)
```

```{r missingvars, echo=TRUE}
suspicious_levels <- c("UNABLE TO DETERMINE", "UNKNOWN")

new_replace_with_na <- function(df, condition) {
  tempdf <- df
  tempdf[rlang::as_function(condition)(tempdf)] <- NA
  return(tempdf)
}

crashes_new <- new_replace_with_na(crashes, condition = ~.x %in% suspicious_levels)

```


```{r resample, echo=TRUE}
miss_var_summary(crashes_new)
```

